services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: ai_api
    command: >
      uvicorn apps.api.main:app
      --host 0.0.0.0
      --port 8081
      --timeout-keep-alive 75
    volumes:
      - .:/app
    env_file: config/.env  
    environment:
      - PYTHONPATH=/app
    depends_on:
      valkey:
        condition: service_healthy
    ports:
      - "8081:8081"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    container_name: ai_worker
    # 현재 구조에 맞게 수정
    command: >
      celery -A packages.presentation.worker.celery_app.celery_app
      worker -l info
      -Q ai
    volumes:
      - .:/app
    env_file: config/.env  
    environment:
      - PYTHONPATH=/app
    depends_on:
      valkey:
        condition: service_healthy
    restart: unless-stopped

volumes:
  valkey_data:
